### ISSUE TITLE
Demos should scale themselves to fit their content

### ISSUE THREAD

**Issue by justinbmeyer** [bit-docs/bit-docs-tag-demo#4]
The demos used to "grow" to contain all their content (up to 600 px high).  We should bring that back:

<img width="1390" alt="cursor_and_canjs_-_data" src="https://cloud.githubusercontent.com/assets/78602/24937704/1b65a12e-1ef8-11e7-8e87-41a6529a5709.png">

**Comment by imaustink** [comment]
The ```@demo``` tag seems to use an iframe for the preview. As far as I can tell, there is no event to listen for when the JavaScript has run within an iframe. The ```load``` event is the closest thing I can find thus far and is too early. The height of the iframe is always 150px on ```load``` since the render hasn't happened yet, so without doing some dirty checking, I don't believe this could work with an iframe.

I looked through the commit history and it looks like it's always used an iframe. Is it possible you are remembering this feature from something else or have I missed something?

**Comment by justinbmeyer** [comment]
It didn't use load other than to begin polling. You checked documentjs out?

**Comment by imaustink** [comment]
Are you saying pollling/dirty checking is an acceptable solution for this?
Yes, I have looked at documentjs. As far as I can tell it doesn't use an iframe for the [```@demo```](https://github.com/bitovi/documentjs/blob/b15ea525de6221f3ed26062fe12b985768f68baf/lib/tags/demo.js) tag. bit-docs' [```@demo```](https://github.com/bit-docs/bit-docs-tag-demo/blob/master/demo_frame.js) tag definitely uses an iframe though.

**Comment by justinbmeyer** [comment]
It does use an iframe.  here's where the polling happens: https://github.com/bitovi/documentjs/blob/master/site/default/static/demo_frame.js#L60

**Comment by justinbmeyer** [comment]
With modern browsers, there maybe better solutions to this.  Nils's element resize library might be able to know when the `body`'s dimensions changed (as opposed to the window's resize).  Otherwise, polling is ok because it only needs to happen every second or so.

**Comment by imaustink** [comment]
Okay awesome, thanks! This is really helpful!
